// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgpetmgxzsqxmtnufzfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncGV0bWd4enNxeG10bnVmemZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzgyNzIsImV4cCI6MjA2ODgxNDI3Mn0.yKpg0MoFVh2t5AfI6wqd3D-ACs-sr8p5VIQXiDAjQLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});